(() => {
  const ZH = {
    "Home":"首頁","Consumer RWA":"消費級 RWA","Ecosystem":"生態系統","News":"新聞","Contact":"聯絡我們","Menu":"選單",
    "RWA.LTD · CONSUMER RWA INFRASTRUCTURE":"RWA.LTD · 消費級 RWA 基礎設施","Connecting Real-World Assets":"連接現實世界資產","On-Chain Circulation ·":"鏈上流通 ·","Creating Platform Value":"創造平台價值",
    "RWA.LTD connects real goods, services and commercial rights with transparent digital representation, on-chain circulation and real-world fulfilment.":"RWA.LTD 透過透明的數位化表達、鏈上流通與現實履約，連接實體商品、服務及商業權益。",
    "Explore Consumer RWA":"探索消費級 RWA","Watch the Film":"觀看影片","PRODUCTS & BRANDS":"產品與品牌","COMMERCE":"商業","FULFILMENT":"履約",
    "ABOUT RWA.LTD":"關於 RWA.LTD","Infrastructure for the future":"面向未來的基礎設施","of":"服務於","real-world digital commerce.":"現實世界數位商業。",
    "RWA.LTD is a Consumer RWA platform that helps brands, project owners and merchants issue, circulate and redeem digital commercial rights backed by real-world assets and services.":"RWA.LTD 是一個消費級 RWA 平台，協助品牌、項目方及商戶發行、流通和兌現由現實資產與服務支持的數位商業權益。",
    "We connect project structure, digital deployment, communication, platform circulation and fulfilment within one coherent lifecycle.":"我們在同一完整生命週期內連接項目架構、數位部署、品牌傳播、平台流通與履約。",
    "Discover our model":"了解我們的模式","REAL VALUE":"真實價值","DIGITAL RIGHTS":"數位權益","CONNECTED COMMERCE":"互聯商業","CONSUMER RWA MODEL":"消費級 RWA 模式",
    "From physical goods and services to":"從實體商品與服務到","manageable digital rights.":"可管理的數位權益。","Real Commercial Value":"真實商業價值","Goods, services, memberships and benefits grounded in real commerce.":"以真實商業為基礎的商品、服務、會籍與權益。",
    "Digital Representation":"數位化表達","Rights represented digitally with clear rules and verifiable project materials.":"以清晰規則及可驗證項目資料將權益數位化。",
    "Circulation & Redemption":"流通與兌現","Connected circulation with a route back to real products and services.":"打通流通渠道，並可回到真實產品與服務。",
    "SOLUTIONS":"解決方案","From idea to issuance,":"從構想到發行，","circulation and redemption.":"再到流通與兌現。","Explore the lifecycle":"探索完整生命週期",
    "Issuance &":"發行與","Redemption Design":"兌現設計","Token rules, rights structure and redemption logic.":"代幣規則、權益架構與兌現邏輯。","Core Project":"核心項目","Materials":"資料","Whitepapers, project guides and essential documentation.":"白皮書、項目指南及必要文件。",
    "Blockchain":"區塊鏈","Deployment":"部署","Secure, scalable deployment aligned with the project model.":"配合項目模式進行安全、可擴展的部署。","Launch & Brand":"發布與品牌","Communication":"傳播","Go-to-market storytelling and project communication.":"市場發布敘事與項目傳播。",
    "Platform":"平台","Circulation":"流通","Connections across platforms, users and commerce channels.":"連接平台、用戶與商業渠道。","Redemption &":"兌現與","Real-world delivery, service access and benefit fulfilment.":"現實世界交付、服務使用及權益履約。",
    "Real Goods & Services":"真實商品與服務","Digital Rights":"數位權益","Issuance":"發行","Redemption":"兌現","ANIMATED PLATFORM FILM":"平台動態影片","RWA.LTD Platform":"RWA.LTD 平台","Driving Real Value On-Chain.":"推動真實價值上鏈。",
    "See how real-world assets move from definition and issuance to circulation and fulfilment.":"了解現實世界資產如何從定義與發行走向流通及履約。","RWA.LTD / PLATFORM FILM":"RWA.LTD / 平台影片",
    "SELECTED ECOSYSTEM PROJECTS":"精選生態項目","Real projects.":"真實項目。","Real commercial value.":"真實商業價值。","View the ecosystem":"查看生態系統","Health & Wellness":"健康與生活","Explore ↗":"探索 ↗","Platform Ecosystem":"平台生態","Jewellery & Digital Rights":"珠寶與數位權益","Media & Services":"媒體與服務","Consumer Goods":"消費品",
    "DOCUMENTS & TRUST":"文件與信任","White Paper":"白皮書","Platform vision, structure and operating model.":"平台願景、架構及營運模式。","Project Guide":"項目指南","A practical guide for brands and project teams.":"面向品牌與項目團隊的實用指南。","Project White Papers":"項目白皮書","Open a token detail page in the RWA Mall to view its project white paper.":"在 RWA 商城開啟代幣詳情頁，查看該項目的白皮書。","Token & Project Details":"代幣與項目詳情","Explore listed projects, token information and available project materials.":"探索已上架項目、代幣資訊及可用項目資料。","Compliance & Legal Notes":"合規與法律說明","Project information, risk and compliance notes.":"項目資訊、風險及合規說明。","Review FAQs covering platform, account, verification and regulatory information.":"查看涵蓋平台、帳戶、身份驗證及監管資訊的常見問題。","Build the next generation of":"共建下一代","Discuss Your Project":"洽談您的項目","Connecting real-world commerce with digital infrastructure.":"連接現實商業與數位基礎設施。",
    "COMPANY":"公司","About":"關於我們","Projects":"項目","Issuance & Redemption":"發行與兌現","Platform Circulation":"平台流通","RESOURCES":"資源","Developer Guide":"開發者指南","Documentation":"技術文件","CONTACT":"聯絡我們","Hong Kong":"香港","© 2026 RWA.LTD. All rights reserved.":"© 2026 RWA.LTD. 版權所有。",
    "Real commerce.":"真實商業。","Digital rights.":"數位權益。","One":"一個","connected lifecycle.":"互聯的生命週期。","RWA.LTD connects real goods and services with identifiable digital commercial rights that can be issued, circulated and redeemed.":"RWA.LTD 將真實商品與服務連接至可識別、可發行、可流通及可兌現的數位商業權益。",
    "Lifecycle":"生命週期","How Consumer RWA works":"消費級 RWA 如何運作","A physical item, service or commercial entitlement is verified and represented digitally.":"實體商品、服務或商業權益經核驗後，以數位形式呈現。","Ownership":"所有權","The right is assigned to its owner and recorded through verifiable infrastructure.":"權益分配予持有人，並透過可驗證基礎設施記錄。","Transfer":"轉移","Ownership can move securely with a clear and traceable record of provenance.":"所有權可安全轉移，並保留清晰可追溯的來源記錄。","The right can be redeemed to unlock a product, service or real-world utility.":"權益可兌現為產品、服務或現實用途。",
    "Built for consumer trust":"為消費者信任而設","Verifiable. Portable.":"可驗證、可攜帶。","Redeemable.":"可兌現。","Cryptographically verifiable ownership":"以密碼學驗證所有權","Portable across supported platforms and jurisdictions":"可跨支援的平台與司法管轄區使用","Redeemable for real-world utility and experiences":"可兌現現實用途與體驗","Real value. Real utilities":"真實價值，真實用途","Unlock more from":"釋放更多","what you own.":"您所擁有的價值。","Connect commercial rights with loyalty, warranties, memberships, upgrades and other real-world utility.":"將商業權益連接至忠誠計劃、保養、會籍、升級及其他現實用途。","Learn how it works":"了解運作方式",
    "Developer & integrator resources":"開發者與整合商資源","Resources & support":"資源與支援","Continue with RWA.LTD":"繼續探索 RWA.LTD","Core concepts and integration patterns.":"核心概念與整合模式。","Smart Contract Docs":"智能合約文件","Contract interfaces, standards and examples.":"合約介面、標準與範例。","API Reference":"API 參考","Issuance, transfer and redemption services.":"發行、轉移及兌現服務。","RWA Mall":"RWA 商城","Explore tokens, project details and project white papers.":"探索代幣、項目詳情及項目白皮書。","FAQ & Legal Information":"常見問題與法律資訊","Account, verification, platform and regulatory guidance.":"帳戶、身份驗證、平台及監管指引。","Integration Enquiries":"整合接入諮詢","Discuss issuance, circulation and redemption requirements.":"洽談發行、流通及兌現需求。","Need access or support?":"需要接入或支援？","Our team partners with platforms, brands and infrastructure providers.":"我們的團隊與平台、品牌及基礎設施供應商合作。","Contact us":"聯絡我們","© RWA.LTD. All rights reserved.":"© RWA.LTD. 版權所有。","Privacy Policy":"私隱政策","Terms of Use":"使用條款",
    "RWA.LTD ECOSYSTEM":"RWA.LTD 生態系統","One ecosystem.":"一個生態系統。","Real projects.":"真實項目。","Connected value.":"互聯價值。","RWA.LTD connects project owners, digital infrastructure, platforms, commerce and fulfilment.":"RWA.LTD 連接項目方、數位基礎設施、平台、商業與履約。","Explore the ecosystem":"探索生態系統","PLATFORM TOKEN":"平台代幣","Connected infrastructure":"互聯基礎設施","Project owners":"項目方","Infrastructure":"基礎設施","Platforms":"平台","Commerce":"商業","Fulfilment":"履約",
    "HOW VALUE MOVES":"價值如何流動","From project to real-world utility.":"從項目走向現實用途。","One connected path from the underlying opportunity to circulation and fulfilment.":"以一條互聯路徑，將底層機會連接至流通與履約。","Project":"項目","Real-world value identified.":"識別現實世界價值。","Structure":"架構","Rights and rules defined.":"定義權益與規則。","Issue":"發行","Digital representation issued.":"發行數位化權益。","Circulate":"流通","Connected across platforms.":"連接不同平台。","Redeem":"兌現","Utility returns to the real world.":"用途回到現實世界。",
    "RWA TOKEN / PLATFORM TOKEN":"RWA 代幣 / 平台代幣","The connective layer":"連接整個生態的","of the ecosystem.":"核心層。","The RWA token represents the platform layer connecting participating projects, infrastructure and circulation channels.":"RWA 代幣代表平台層，連接參與項目、基礎設施及流通渠道。","Connect with RWA.LTD":"連接 RWA.LTD","Ecosystem coordination":"生態協調","Connect projects with shared infrastructure.":"以共享基礎設施連接項目。","Platform participation":"平台參與","Support participation across the RWA.LTD network.":"支援參與 RWA.LTD 網絡。","Connected utility":"互聯用途","Link circulation with real-world fulfilment.":"連接流通與現實履約。",
    "SELECTED PROJECTS":"精選項目","Projects within the ecosystem.":"生態系統中的項目。","Real project tokens connected through the RWA.LTD platform ecosystem.":"透過 RWA.LTD 平台生態連接真實項目代幣。","01 / ECOSYSTEM PROJECT":"01 / 生態項目","02 / ECOSYSTEM PROJECT":"02 / 生態項目","03 / ECOSYSTEM PROJECT":"03 / 生態項目","04 / ECOSYSTEM PROJECT":"04 / 生態項目","Explore":"探索","BUILD WITH RWA.LTD":"與 RWA.LTD 共建","Build within":"在生態系統內","the ecosystem.":"共同建設。","Connect your project with the infrastructure, platforms and channels needed to move from real-world value to real-world utility.":"將您的項目連接至所需的基礎設施、平台與渠道，推動真實價值走向現實用途。","GET IN TOUCH":"聯絡我們",
    "CONTACT RWA.LTD":"聯絡 RWA.LTD","Let’s build real-world":"讓我們共同創造","value together.":"真實世界價值。","Connect your project with RWA.LTD infrastructure, platforms and ecosystem.":"將您的項目連接至 RWA.LTD 的基礎設施、平台與生態系統。","Project enquiry":"項目諮詢","Explore opportunities for real-world projects.":"探索現實世界項目的合作機會。","Platform integration":"平台整合","Connect with RWA.LTD infrastructure and platforms.":"接入 RWA.LTD 基礎設施與平台。","General contact":"一般查詢","Reach out to our team for general enquiries.":"就一般查詢聯絡我們的團隊。","Start a conversation":"開始對話","Tell us about your project.":"告訴我們您的項目。","We’ll connect you with the right team.":"我們會安排合適的團隊與您聯絡。","Name":"姓名","Company / Project":"公司 / 項目","Email":"電郵","Region":"地區","Select region":"選擇地區","Mainland China":"中國內地","Asia Pacific":"亞太地區","Europe":"歐洲","North America":"北美洲","Other":"其他","What are you looking to build?":"您希望建設甚麼？","Send enquiry":"提交查詢","By submitting an enquiry, you agree that RWA.LTD may contact you regarding your request.":"提交查詢即表示您同意 RWA.LTD 就您的需求與您聯絡。","Tell us about the project":"介紹您的項目","Share your goals and key requirements.":"分享您的目標與主要需求。","We review the opportunity":"我們評估合作機會","Our team considers how RWA.LTD can support the initiative.":"我們的團隊將評估 RWA.LTD 如何支援此項目。","Continue the conversation":"繼續溝通","We connect to explore the next steps together.":"我們將與您聯絡，共同探討下一步。",
    "THE COMPLETE RWA LIFECYCLE":"完整 RWA 生命週期","From real-world asset":"從現實世界資產","to real-world value.":"走向現實世界價值。","A practical end-to-end process for structuring consumer rights, enabling controlled circulation and completing real-world fulfilment.":"一套實用的端到端流程，涵蓋消費者權益架構、受控流通及現實世界履約。","PRIMARY ISSUANCE":"首次發行","Turn commercial value into a verifiable digital right.":"將商業價值轉化為可驗證的數位權益。","Asset Review":"資產審查","Confirm the product, service or entitlement and its eligibility.":"確認產品、服務或權益及其合資格性。","Rights Structure":"權益架構","Define ownership, usage terms, restrictions and redemption rules.":"定義所有權、使用條款、限制及兌現規則。","Project Materials":"項目資料","Prepare disclosures, supporting evidence and project documentation.":"準備披露文件、支持證據及項目資料。","Digital Issuance":"數位發行","Issue the digital rights and record their initial ownership.":"發行數位權益並記錄初始所有權。","Outcome":"成果","Verifiable project materials":"可驗證項目資料","Clear rights terms, supporting evidence and an auditable issuance record.":"清晰的權益條款、支持證據及可審計的發行記錄。","CIRCULATION":"流通","Move consumer rights with transparent ownership records.":"透過透明的所有權記錄流轉消費者權益。","Project Listing":"項目上架","Present the project, rights, terms and available materials.":"展示項目、權益、條款及可用資料。","Buyer Match":"買方匹配","Connect eligible participants under clear transaction conditions.":"按清晰交易條件連接合資格參與者。","Rights Transfer":"權益轉移","Transfer the digital right securely after settlement.":"結算後安全轉移數位權益。","Ownership Record":"所有權記錄","Record the new holder and preserve a traceable audit trail.":"記錄新持有人並保留可追溯的審計軌跡。","Traceable ownership":"可追溯所有權","Every transfer is connected to a clear, verifiable ownership record.":"每次轉移均連接至清晰、可驗證的所有權記錄。","REDEMPTION":"兌現","Return the digital right to real products, services and benefits.":"將數位權益兌現為真實產品、服務及福利。","Redemption Request":"兌現申請","The holder submits a request with the required information.":"持有人提交申請及所需資料。","Ownership Verification":"所有權驗證","Confirm ownership, eligibility and the applicable redemption terms.":"確認所有權、資格及適用的兌現條款。","Product / Service Fulfilment":"產品 / 服務履約","Deliver the agreed product, service, access or member benefit.":"交付約定的產品、服務、使用權或會員福利。","Completion":"完成","Record fulfilment and close or update the digital right.":"記錄履約，並結束或更新數位權益。","Real-world fulfilment":"現實世界履約","The digital record closes the loop with proof of delivery or service completion.":"數位記錄以交付或服務完成證明形成完整閉環。","HEALTH":"健康","GOODS":"商品","MEMBERSHIP":"會籍","SELLER":"賣方","BUYER":"買方","Digital Right":"數位權益","Ownership verified":"所有權已驗證","Transfer complete":"轉移完成","New owner recorded":"新持有人已記錄","REDEEMED":"已兌現","Real-world fulfilment complete":"現實世界履約完成",
    "Real-world value. On-chain rights.":"現實世界價值，鏈上權益。","Consumer RWA lets users participate in real-world assets and services through verifiable digital rights—issued on-chain, transferable and redeemable in the real world.":"消費級 RWA 讓用戶透過可驗證的數位權益參與現實世界資產與服務；權益可在鏈上發行、轉移，並於現實世界兌現。","Verifiable Rights":"可驗證權益","Your rights are recorded on-chain and easy to verify.":"您的權益記錄於鏈上，清晰可驗證。","Transfer securely with full transparency and traceability.":"以透明、可追溯的方式安全轉移。","Use your rights to redeem services, products or benefits.":"使用權益兌現服務、產品或福利。","Regulated":"合規保障","Built with compliance and investor protection at every step.":"每個環節均納入合規與權益持有人保障。","Discover Projects":"探索項目","Browse vetted projects across health, lifestyle, art, memberships and consumer services.":"探索涵蓋健康、生活方式、藝術、會籍與消費服務的已審核項目。","Acquire Rights":"取得權益","Buy digital rights securely on-chain.":"在鏈上安全取得數位權益。","Transfer or Hold":"轉移或持有","Transfer to others or hold as a digital right.":"可轉移予他人，亦可持續持有數位權益。","Redeem & Enjoy":"兌現及使用","Redeem your rights for real-world products, services or experiences.":"將權益兌現為現實世界產品、服務或體驗。","The Complete RWA Lifecycle":"完整 RWA 生命週期","From real-world asset to real-world value.":"從現實世界資產走向現實世界價值。","Primary Issuance":"首次發行","Establish the asset, define rights and issue verifiable digital rights.":"確立資產、定義權益並發行可驗證數位權益。","Circulation":"流通","List, match and transfer rights with full transparency.":"以透明方式上架、匹配及轉移權益。","Redemption":"兌現","Redeem rights for real-world value and close the loop.":"將權益兌現為現實價值，完成完整閉環。","Documents":"文件","Trust":"信任","Every project is backed by clear documents and compliance oversight to protect right holders.":"每個項目均以清晰文件及合規監督為基礎，保障權益持有人。","All documents are on-chain verifiable. Nothing is hidden. Everything is auditable.":"所有文件均可在鏈上驗證；資料透明，記錄可審計。",
    "On-Chain":"鏈上","Verified":"可驗證","Rights":"權益","Immutable":"不可篡改","Records":"記錄","Transparent":"透明","Real-World":"現實世界","Transferable":"可轉移","Redeemable":"可兌現","How Consumer":"消費級 RWA","RWA works":"如何運作",
    "Assess the asset, validate eligibility and compliance.":"評估資產並核實其資格及合規性。","Define rights, terms and restrictions.":"定義權益、條款及限制。","Prepare materials and disclosures for transparency.":"準備項目資料及披露文件，確保資訊透明。","Mint rights on-chain for the initial holders.":"為初始持有人在鏈上鑄造權益。","OUTCOME":"成果","Clear rights terms and authenticated disclosures.":"提供清晰的權益條款及經核實的披露資料。",
    "Projects are listed with key details and terms.":"項目連同主要資料及條款上架。","Buyers discover projects and agree to terms.":"買方探索項目並確認相關條款。","Ownership is transferred on-chain securely.":"所有權在鏈上安全轉移。","Every change is recorded in an immutable audit trail.":"每次變更均記錄於不可篡改的審計軌跡。","Transparent circulation with an immutable on-chain record.":"透過不可篡改的鏈上記錄實現透明流通。",
    "Right holder submits a redemption request.":"權益持有人提交兌現申請。","Verify ownership and on-chain eligibility.":"驗證所有權及鏈上兌現資格。","Deliver the agreed product, service or experience.":"交付約定的產品、服務或體驗。","Redemption is completed and recorded on-chain.":"完成兌現並在鏈上記錄。","Rights are fulfilled and settlement is recorded with proof of completion.":"權益完成履約，並以完成證明記錄結算。",
    "Project overview & use case":"項目概覽及使用場景","Asset details & valuation basis":"資產詳情及估值基礎","Rights, terms & restrictions":"權益、條款及限制","Risk factors & disclosures":"風險因素及披露","Token information & structure":"代幣資訊及架構","Rights & entitlements":"權益及持有人權利","Supply, pricing & fees":"供應量、定價及費用","Issuance & circulation rules":"發行及流通規則","Regulatory framework compliance":"監管框架合規","KYC / AML procedures":"KYC / AML 程序","Investor protection measures":"投資者保障措施","Legal agreements & policies":"法律協議及政策",
    "REAL WORLD ASSETS":"現實世界資產","BUILT FOR THE REAL WORLD":"為現實世界而建","RWA SOLUTIONS":"RWA 解決方案","Institutional RWA":"機構級 RWA","Tokenization Services":"代幣化服務","Compliance & Risk":"合規與風險","Technology":"技術","ECOSYSTEM":"生態系統","Ecosystem Partners":"生態合作夥伴","Custody Partners":"託管合作夥伴","Marketplace Partners":"市場合作夥伴","Developer Resources":"開發者資源","RESOURCES":"資源","Insights":"洞察","Whitepapers":"白皮書","Case Studies":"案例研究","News & Events":"新聞與活動","Help Center":"幫助中心","COMPANY":"公司","About RWA.LTD":"關於 RWA.LTD","Leadership":"管理團隊","Careers":"招聘職位","Contact Us":"聯絡我們","Legal":"法律聲明",
    "Change language":"選擇語言","Main navigation":"主要導覽","RWA.LTD home":"RWA.LTD 首頁","RWA.LTD platform token and connected rights":"RWA.LTD 平台代幣及互聯權益","Primary issuance asset categories":"首次發行資產類別","Consumer rights circulation and ownership record":"消費者權益流通及所有權記錄","Real-world redemption and fulfilment":"現實世界兌現及履約",
    "Connected platforms for":"互聯平台，服務於","consumer RWA commerce.":"消費級 RWA 商業。","One operating ecosystem connects merchant onboarding, consumer-right issuance, marketplace participation, redemption and commercial support tools.":"一個營運生態系統連接商戶入駐、消費權益發行、市場參與、兌現及商業支援工具。","Explore the platform stack":"探索平台架構","Three connected RWA.LTD ecosystem platforms":"三個互聯的 RWA.LTD 生態平台","01 / MERCHANT ENTRY":"01 / 商戶入口","Merchant onboarding and operations":"商戶入駐及營運","02 / CORE PLATFORM":"02 / 核心平台","Issuance, trading and redemption infrastructure":"發行、交易及兌現基礎設施","03 / CONSUMER ACCESS":"03 / 消費者入口","Product discovery and redemption scenarios":"產品探索及兌現場景","COMPLIANCE & MONITORING":"合規與監察","DATA & AI TOOLS":"數據與 AI 工具","REAL-WORLD FULFILMENT":"現實世界履約",
    "THREE CONNECTED PLATFORMS":"三個互聯平台","Distinct roles. One commercial system.":"角色各異，同屬一個商業系統。","Each platform serves a different participant and removes a different operational barrier.":"每個平台服務不同參與者，並解決不同的營運障礙。","MERCHANT WORKFLOW":"商戶工作流程","Supports merchant registration, business-information submission, payment workflows, order management and merchant-side operations.":"支援商戶註冊、商業資料提交、付款流程、訂單管理及商戶端營運。","Merchant operations":"商戶營運","FLAGSHIP PLATFORM":"旗艦平台","Provides the infrastructure for issuing, trading and redeeming tokenized consumer rights connected to real goods and services.":"為連接真實商品與服務的代幣化消費權益提供發行、交易及兌現基礎設施。","Core infrastructure":"核心基礎設施","MALL ECOSYSTEM":"商城生態","Creates a consumer-facing environment for product display, participation, redemption flows and token-enabled engagement.":"建立面向消費者的產品展示、參與、兌現流程及代幣化互動環境。","Consumer access":"消費者入口",
    "ECOSYSTEM ROLES":"生態角色","What connects around the platforms.":"平台周邊連接的關鍵角色。","The ecosystem extends beyond token projects into the operational and professional capabilities required to run them.":"生態系統不止於代幣項目，更涵蓋項目營運所需的實務及專業能力。","Merchants & project owners":"商戶與項目方","Define products, services, rights, commercial terms and fulfilment commitments.":"定義產品、服務、權益、商業條款及履約承諾。","Issuance infrastructure":"發行基礎設施","Structures consumer rights for controlled issuance, ownership records and circulation.":"為消費權益建立受控發行、所有權記錄及流通架構。","Marketplaces & users":"市場與用戶","Connects product discovery, user participation and supported trading scenarios.":"連接產品探索、用戶參與及受支援的交易場景。","Redemption operations":"兌現營運","Links digital rights back to products, services, access and real-world delivery.":"將數位權益連接回產品、服務、使用權及現實交付。","Compliance & monitoring":"合規與監察","Supports due diligence, agreements, traceability and operational transparency.":"支援盡職調查、協議安排、可追溯性及營運透明度。","Data & AI tools":"數據與 AI 工具","Supports market-information extraction, comparison tools and operating efficiency.":"支援市場資訊提取、比較工具及營運效率提升。",
    "OPERATING LAYERS":"營運層級","Technology is only one part of the ecosystem.":"技術只是生態系統的一部分。","Off-chain operations":"鏈下營運","Issuer due diligence, legal arrangements, business information and practical workflow design.":"涵蓋發行方盡職調查、法律安排、商業資料及實際工作流程設計。","Application layer":"應用層","Merchant onboarding, issuance, market participation, redemption and consumer commerce tools.":"涵蓋商戶入駐、發行、市場參與、兌現及消費商業工具。","Hybrid monitoring":"混合監察","Traceability, verification and operational transparency across commercial use cases.":"為各類商業場景提供可追溯性、驗證及營運透明度。","CONNECT TO THE ECOSYSTEM":"接入生態系統","Choose the right entry point.":"選擇合適的接入點。","Bring a project, integrate a merchant workflow, connect a marketplace or discuss the operational support your use case requires.":"帶來您的項目、整合商戶流程、連接市場，或洽談應用場景所需的營運支援。","CONTACT RWA.LTD":"聯絡 RWA.LTD"
  };
  const traditionalMap = {"简":"簡","体":"體","页":"頁","费":"費","级":"級","现":"現","实":"實","产":"產","资":"資","链":"鏈","创":"創","连":"連","数":"數","权":"權","发":"發","项":"項","与":"與","营":"營","务":"務","为":"為","从":"從","验":"驗","证":"證","规":"規","则":"則","兑":"兌","过":"過","动":"動","观":"觀","统":"統","络":"絡","价":"價","础":"礎","设":"設","业":"業","历":"歷","拥":"擁","转":"轉","录":"錄","归":"歸","属":"屬","阅":"閱","档":"檔","隐":"隱","条":"條","联":"聯","系":"繫","问":"問","询":"詢","择":"擇","亚":"亞","欧":"歐","区":"區","华":"華","际":"際","开":"開","关":"關","内":"內","沟":"溝","构":"構","护":"護","应":"應","参":"參","网":"網","层":"層","结":"結","传":"傳","递":"遞","复":"復","杂":"雜","储":"儲","拟":"擬","写":"寫","导":"導","读":"讀","识":"識","别":"別","积":"積","极":"極","标":"標","题":"題","签":"簽","选":"選","单":"單","户":"戶","这":"這","个":"個","会":"會","将":"將","进":"進","对":"對","话":"話","团":"團","队":"隊","协":"協","调":"調","续":"續","习":"習","经":"經","济":"濟","马":"馬","国":"國","么":"麼","术":"術","汇":"匯","众":"眾","运":"運","达":"達","争":"爭","场":"場","径":"徑","响":"響","办":"辦","较":"較","销":"銷","启":"啟","类":"類","据":"據","范":"範","机":"機","态":"態","讯":"訊","说":"說","险":"險","扩":"擴","币":"幣","撑":"撐","领":"領","周":"週"};
  const toSimplified = (s) => {
    const phrase = {"聯絡":"联系","私隱":"隐私","會籍":"会员资格","項目方":"项目方","消費級":"消费级","數位":"数字","兌現":"兑换","履約":"履约","甚麼":"什么","電郵":"邮箱","保養":"保修","亞太地區":"亚太地区","中國內地":"中国大陆"};
    let out=s; Object.entries(phrase).forEach(([a,b])=>out=out.split(a).join(b));
    const reverse={}; Object.entries(traditionalMap).forEach(([s,t])=>reverse[t]=s);
    return [...out].map(c=>reverse[c]||c).join("");
  };
  const originals = new WeakMap();
  const attributeOriginals = new WeakMap();
  const labels = {en:"EN", "zh-Hant":"繁中", "zh-Hans":"简中"};
  const translate = (text, lang) => {
    if(lang==="en") return text;
    const traditional=ZH[text] || text;
    return lang==="zh-Hans" ? toSimplified(traditional) : traditional;
  };
  function apply(lang){
    if(!labels[lang]) lang="en";
    document.documentElement.lang=lang==="en"?"en":lang;
    document.documentElement.dir="ltr";
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
    const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node=>{
      if(node.parentElement?.closest(".language-menu")) return;
      if(!originals.has(node)) originals.set(node,node.nodeValue);
      const original=originals.get(node), trimmed=original.trim();
      if(!trimmed) return;
      const lead=original.match(/^\s*/)[0], trail=original.match(/\s*$/)[0];
      node.nodeValue=lead+translate(trimmed,lang)+trail;
    });
    document.querySelectorAll("[alt],[title],[aria-label]").forEach(el=>{
      if(!attributeOriginals.has(el)){
        const saved={};["alt","title","aria-label"].forEach(name=>{if(el.hasAttribute(name))saved[name]=el.getAttribute(name)});attributeOriginals.set(el,saved);
      }
      Object.entries(attributeOriginals.get(el)).forEach(([name,value])=>el.setAttribute(name,translate(value,lang)));
    });
    document.querySelectorAll("[data-language-current]").forEach(el=>el.textContent=labels[lang]);
    document.querySelectorAll(".language-menu button").forEach(el=>el.classList.toggle("active",el.dataset.language===lang));
    localStorage.setItem("rwa-language",lang);
    window.dispatchEvent(new CustomEvent("rwa:languagechange",{detail:{language:lang}}));
  }
  function mount(){
    document.querySelectorAll(".global-header .language,.global-header .v10-lang").forEach(control=>{
      control.setAttribute("role","button");control.setAttribute("tabindex","0");control.setAttribute("aria-label","Change language");
      control.innerHTML='<span data-language-current>EN</span><span aria-hidden="true">⌄</span>';
      const menu=document.createElement("div");menu.className="language-menu";menu.innerHTML='<button type="button" data-language="en">English</button><button type="button" data-language="zh-Hant">繁體中文</button><button type="button" data-language="zh-Hans">简体中文</button>';
      control.appendChild(menu);
      const toggle=e=>{e.stopPropagation();control.classList.toggle("open")};
      control.addEventListener("click",toggle);control.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();toggle(e)}});
      menu.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();apply(btn.dataset.language);control.classList.remove("open")}));
    });
    document.addEventListener("click",()=>document.querySelectorAll(".global-header .language.open,.global-header .v10-lang.open").forEach(x=>x.classList.remove("open")));
    apply(localStorage.getItem("rwa-language")||"en");
  }
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",mount):mount();
})();
